package publicnews

import (
	"strings"
	"testing"
)

func TestSourceLooksLikeNewsCollectionRejectsRoundups(t *testing.T) {
	sinaBody := strings.Join([]string{
		"1、公司否认产品延期",
		"https://news.example.com/story-1",
		"2、监管机构启动调查",
		"https://news.example.com/story-2",
		"3、合作伙伴发布新平台",
		"https://news.example.com/story-3",
		"4、供应商开始交付",
		"https://news.example.com/story-4",
		"5、公司公布产品路线",
		"https://news.example.com/story-5",
	}, "\n")
	if !SourceLooksLikeNewsCollection("示例公司热点小时报_今日实时热点速递", sinaBody) {
		t.Fatal("expected explicit hourly roundup to be classified as a collection")
	}

	tencentBody := "**速览：** 多项动态。### 1. 产品投产 来源:媒体甲>>### 2. 监管调查 来源:媒体乙>>### 3. 合作升级 来源:媒体丙>>### 4. 供应变化 来源:媒体丁>>### 5. 股价波动 来源:媒体戊>>"
	if !SourceLooksLikeNewsCollection("示例公司动态", tencentBody) {
		t.Fatal("expected multi-publisher digest body to be classified as a collection")
	}
}

func TestSourceLooksLikeNewsCollectionKeepsSingleStoryAnalysis(t *testing.T) {
	body := strings.Join([]string{
		"发布时间: 2026-07-16 10:00",
		"1. 公司确认新系统已经进入生产阶段，并说明首批交付时间。",
		"2. 监管文件解释了适用范围，但没有改变此前许可条件。",
		"3. 两名客户分别确认测试计划，商业效果仍需后续观察。",
		"记者采访公司和客户并核对监管文件后，补充了上述时间线。",
	}, "\n")
	if SourceLooksLikeNewsCollection("示例公司确认新系统交付计划", body) {
		t.Fatal("expected numbered sections in one reported article to remain usable")
	}
}

func TestSourceLooksLikeNewsCollectionRejectsPortalBodyWithCleanEventExtract(t *testing.T) {
	body := "研究报告 定期财报 公司公告 主要行业 今日热门 本周热门 本月热门 最新推荐 精选研报 更多 >> 百望股份公告董事会批准回购H股计划。客户端下载 正在加载，请稍候"
	if !SourceLooksLikeNewsCollection("百望股份回购H股计划", body) {
		t.Fatal("expected portal-template body to remain a collection surface even when one event can be extracted")
	}
}

func TestLocaleLandingFileRecognizesLocalizedIndexesWithoutRejectingArticles(t *testing.T) {
	for _, segment := range []string{"en.html", "index.da.html", "index.da_DK.html", "home-pt-br.htm"} {
		if !LocaleLandingFile(segment) {
			t.Fatalf("expected %q to be a locale landing file", segment)
		}
	}
	for _, segment := range []string{"ai.html", "release.da.html", "index.latest-update.html", "latest-update.html"} {
		if LocaleLandingFile(segment) {
			t.Fatalf("expected article-like %q not to be a locale landing file", segment)
		}
	}
}

func TestAIGeneratedSourceTextRecognizesDisclosuresWithoutMatchingReportingTopics(t *testing.T) {
	for _, text := range []string{
		"免责声明：本文内容由开放的智能模型自动生成，仅供参考。",
		"本文由AI大模型基于公开信息生成，不代表网站观点。",
		"This content was generated by an artificial intelligence language model.",
	} {
		if !AIGeneratedSourceText(text) {
			t.Fatalf("expected AI-generation disclosure to be detected: %q", text)
		}
	}
	if AIGeneratedSourceText("研究人员分析了人工智能模型自动生成内容的监管风险，记者随后采访了政策制定者。") {
		t.Fatal("expected reporting about generated content not to be treated as an AI-generation disclosure")
	}
}
