package publicnews

import (
	"net/url"
	"regexp"
	"strings"
)

var (
	newsCollectionNumberedLinePattern = regexp.MustCompile(`(?m)^\s*(?:#{1,6}\s*)?\d{1,2}\s*[、.．)]\s*\S`)
	newsCollectionMarkdownItemPattern = regexp.MustCompile(`#{2,6}\s*\d{1,2}\s*[、.．)]\s*\S`)
	newsCollectionURLPattern          = regexp.MustCompile(`(?i)https?://`)
	newsCollectionAttributionPattern  = regexp.MustCompile(`(?i)(?:来源|source)\s*[:：]`)
	newsCollectionDatedEntryPattern   = regexp.MustCompile(`(?im)^\s*(?:(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+\d{1,2},\s+20\d{2},\s+\d{1,2}:\d{2}|20\d{2}[-/.]\d{1,2}[-/.]\d{1,2}\s+\d{1,2}:\d{2})\b[^\n]{4,}`)
	localeTagPattern                  = regexp.MustCompile(`^[a-z]{2,3}(?:-[a-z0-9]{2,8})*$`)
	aiGeneratedDisclosurePattern      = regexp.MustCompile(`(?i)(?:本文|本内容|本文内容|以上内容|该内容|content)[^。；\n]{0,24}(?:由|为|was|is)[^。；\n]{0,48}(?:ai|人工智能|智能模型|大模型|语言模型)[^。；\n]{0,48}(?:自动)?生成|content[^.;\n]{0,32}generated\s+by\s+(?:an?\s+)?(?:ai|artificial intelligence|language model)`)
)

// LocaleLandingFile identifies HTML locale selectors and locale-specific
// index files. These are navigation surfaces even when search presents them
// with a recent timestamp and an article-like snippet.
func LocaleLandingFile(segment string) bool {
	segment = strings.ToLower(strings.TrimSpace(segment))
	extension := ""
	for _, candidate := range []string{".html", ".htm"} {
		if strings.HasSuffix(segment, candidate) {
			extension = candidate
			break
		}
	}
	if extension == "" {
		return false
	}
	stem := strings.TrimSuffix(segment, extension)
	stem = strings.ReplaceAll(stem, "_", "-")
	for _, prefix := range []string{"index.", "index-", "home.", "home-"} {
		if strings.HasPrefix(stem, prefix) {
			return localeTagPattern.MatchString(strings.TrimPrefix(stem, prefix))
		}
	}
	switch stem {
	case "en", "en-us", "en-gb", "zh", "zh-cn", "zh-hk", "zh-tw", "ja", "ja-jp", "ko", "ko-kr", "de", "fr", "es", "it", "pt", "pt-br":
		return true
	default:
		return false
	}
}

// SourceLooksLikeNewsCollection identifies roundup, digest, and multi-story
// collection pages. They may help discover a story, but must not count as an
// independently reported article for the selected event.
func SourceLooksLikeNewsCollection(title string, text string) bool {
	title = strings.ToLower(strings.TrimSpace(title))
	for _, marker := range []string{
		"热点小时报", "热点速递", "新闻速递", "资讯速递", "新闻汇总", "资讯汇总",
		"每日汇总", "每周汇总", "一周要闻", "一周资讯", "news roundup", "daily roundup",
		"weekly roundup", "news digest", "daily digest", "weekly digest", "news in brief",
	} {
		if strings.Contains(title, marker) {
			return true
		}
	}

	text = strings.TrimSpace(text)
	if text == "" {
		return false
	}
	if looksLikeChineseSiteNavigationBoilerplate(strings.ToLower(text)) {
		return true
	}
	if datedEntryCount := len(newsCollectionDatedEntryPattern.FindAllStringIndex(text, -1)); datedEntryCount >= 5 ||
		(datedEntryCount >= 3 && genericNewsCollectionTitle(title)) {
		return true
	}
	itemCount := len(newsCollectionNumberedLinePattern.FindAllStringIndex(text, -1))
	if markdownCount := len(newsCollectionMarkdownItemPattern.FindAllStringIndex(text, -1)); markdownCount > itemCount {
		itemCount = markdownCount
	}
	if itemCount < 3 {
		return false
	}
	attributionCount := len(newsCollectionAttributionPattern.FindAllStringIndex(text, -1))
	urlCount := len(newsCollectionURLPattern.FindAllStringIndex(text, -1))
	lowerText := strings.ToLower(text)
	hasDigestLead := containsAnyFold(lowerText, "速览", "要闻速览", "新闻摘要", "news roundup", "news digest")
	return (itemCount >= 5 && (attributionCount >= 3 || urlCount >= 3)) ||
		(hasDigestLead && itemCount >= 3 && attributionCount >= 3)
}

func genericNewsCollectionTitle(title string) bool {
	title = strings.TrimSpace(strings.ToLower(title))
	switch title {
	case "news", "latest", "latest news", "company news", "press releases", "news releases", "新闻", "最新新闻", "公司新闻", "新闻稿":
		return true
	default:
		return false
	}
}

// AIGeneratedSourceText identifies pages that explicitly disclose machine-
// generated editorial content. Such pages may be discovery hints, but they do
// not satisfy grounded public-news evidence or an independent cross-check.
func AIGeneratedSourceText(text string) bool {
	text = strings.ToLower(strings.TrimSpace(text))
	if text == "" {
		return false
	}
	if aiGeneratedDisclosurePattern.MatchString(text) {
		return true
	}
	for _, marker := range []string{
		"美股ai助手",
		"content was generated by ai based on public information",
		"content generated by ai based on public information",
	} {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}

// CommunitySourceURL identifies user-published/community surfaces that must
// not satisfy an independent public-news cross-check on their own.
func CommunitySourceURL(rawURL string) bool {
	parsed, err := url.Parse(strings.TrimSpace(rawURL))
	if err != nil || parsed == nil {
		return false
	}
	host := NormalizeSourceHost(parsed.Hostname())
	for _, communityHost := range []string{
		"caifuhao.eastmoney.com",
		"guba.eastmoney.com",
		"k.sina.cn",
		"xueqiu.com",
		"weibo.cn",
		"weibo.com",
		"reddit.com",
	} {
		if host == communityHost || strings.HasSuffix(host, "."+communityHost) {
			return true
		}
	}
	return false
}

// UserGeneratedSourceText identifies pages whose own disclosure says that the
// content was uploaded by a user and the host only provides a publishing or
// storage surface. Such pages cannot satisfy an independent editorial-source
// cross-check even when they use a publisher-owned domain.
func UserGeneratedSourceText(text string) bool {
	lower := strings.ToLower(strings.TrimSpace(text))
	if lower == "" {
		return false
	}
	chineseUpload := strings.Contains(lower, "用户上传并发布") || strings.Contains(lower, "用户自行上传")
	chinesePlatform := strings.Contains(lower, "自媒体平台") || strings.Contains(lower, "仅提供信息存储空间")
	englishUpload := strings.Contains(lower, "uploaded and posted by the user") || strings.Contains(lower, "user-uploaded content")
	englishPlatform := strings.Contains(lower, "social media platform") || strings.Contains(lower, "provides information storage space")
	return (chineseUpload && chinesePlatform) || (englishUpload && englishPlatform)
}

func evidenceUsesCommunitySurface(evidence Evidence) bool {
	return CommunitySourceURL(evidence.SourceURL) || UserGeneratedSourceText(evidence.groundedText)
}
