package tools

func mergeBrowserCapabilities(base BrowserCapabilities, overlay BrowserCapabilities) BrowserCapabilities {
	return BrowserCapabilities{
		RuntimeStatus:       base.RuntimeStatus || overlay.RuntimeStatus,
		RuntimeWorkbench:    base.RuntimeWorkbench || overlay.RuntimeWorkbench,
		RuntimePrepare:      base.RuntimePrepare || overlay.RuntimePrepare,
		RuntimeCoordinate:   base.RuntimeCoordinate || overlay.RuntimeCoordinate,
		RuntimeStart:        base.RuntimeStart || overlay.RuntimeStart,
		RuntimeRestart:      base.RuntimeRestart || overlay.RuntimeRestart,
		RuntimeStop:         base.RuntimeStop || overlay.RuntimeStop,
		RuntimeCreate:       base.RuntimeCreate || overlay.RuntimeCreate,
		RuntimeDelete:       base.RuntimeDelete || overlay.RuntimeDelete,
		RuntimeSelect:       base.RuntimeSelect || overlay.RuntimeSelect,
		RuntimeClear:        base.RuntimeClear || overlay.RuntimeClear,
		RuntimeClearSession: base.RuntimeClearSession || overlay.RuntimeClearSession,
		RuntimeSelectTarget: base.RuntimeSelectTarget || overlay.RuntimeSelectTarget,
		RuntimeClearTarget:  base.RuntimeClearTarget || overlay.RuntimeClearTarget,
		RuntimeList:         base.RuntimeList || overlay.RuntimeList,
		RuntimeSessions:     base.RuntimeSessions || overlay.RuntimeSessions,
		Open:                base.Open || overlay.Open,
		Navigate:            base.Navigate || overlay.Navigate,
		Tabs:                base.Tabs || overlay.Tabs,
		Extract:             base.Extract || overlay.Extract,
		Snapshot:            base.Snapshot || overlay.Snapshot,
		Screenshot:          base.Screenshot || overlay.Screenshot,
		Console:             base.Console || overlay.Console,
		Requests:            base.Requests || overlay.Requests,
		ResponseBody:        base.ResponseBody || overlay.ResponseBody,
		Errors:              base.Errors || overlay.Errors,
		Cookies:             base.Cookies || overlay.Cookies,
		CookiesSet:          base.CookiesSet || overlay.CookiesSet,
		CookiesClear:        base.CookiesClear || overlay.CookiesClear,
		Storage:             base.Storage || overlay.Storage,
		StorageSet:          base.StorageSet || overlay.StorageSet,
		StorageClear:        base.StorageClear || overlay.StorageClear,
		Highlight:           base.Highlight || overlay.Highlight,
		TraceStart:          base.TraceStart || overlay.TraceStart,
		TraceStop:           base.TraceStop || overlay.TraceStop,
		Download:            base.Download || overlay.Download,
		WaitDownload:        base.WaitDownload || overlay.WaitDownload,
		SavePDF:             base.SavePDF || overlay.SavePDF,
		SaveHTML:            base.SaveHTML || overlay.SaveHTML,
		Dialog:              base.Dialog || overlay.Dialog,
		Upload:              base.Upload || overlay.Upload,
		Press:               base.Press || overlay.Press,
		Hover:               base.Hover || overlay.Hover,
		Drag:                base.Drag || overlay.Drag,
		Select:              base.Select || overlay.Select,
		Fill:                base.Fill || overlay.Fill,
		Resize:              base.Resize || overlay.Resize,
		Click:               base.Click || overlay.Click,
		TypeText:            base.TypeText || overlay.TypeText,
		Evaluate:            base.Evaluate || overlay.Evaluate,
		Wait:                base.Wait || overlay.Wait,
	}
}
